on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile

      - name: Transpile and bundle test script
        run: |
          yarn webpack

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: dist/get-200-status-test.js
